### ISSUE TITLE
DNR priority not respected between session and static rules

### ISSUE THREAD

**Issue by lenacohen** [EFForg/SafariWebExtensionBugs#3]
DNR redirect session rules with a lower priority are applied before / instead of static redirect rules with a higher priority. The only way to get the static rule to apply is to remove the session rule, even though the static rule has a higher priority number. 

I encountered this bug after updating my Safari version from 17.5 to 18.3

Demo Xcode extension: https://github.com/lenacohen/Safari-Test-Extensions/tree/main/dnr-session-vs-static-redirects
- Visit eff.org and test whether it is redirected to newyorktimes.com (lower priority session rule) or washingtonpost.com (higher priority static rule)

Session rule that overrides a static rule of higher priority:
```
let updateRules = await chrome.declarativeNetRequest.updateSessionRules({addRules: [
    {
        id: 2,
        priority: 1,
        action: {
          type: "redirect",
          redirect: {
            url: "http://newyorktimes.com/"
          }
        },
        condition: {
            urlFilter: "||eff.org^",
            resourceTypes: [
                "main_frame"
            ]
        }
      }
]});
```

Static rule that is overridden by a session rule of lower priority:
```
    {
      "id": 1,
      "priority": 2,
      "action": {
        "type": "redirect",
        "redirect": {
          "url": "http://washingtonpost.com/"
        }
      },
      "condition": {
        "urlFilter": "||eff.org^",
        "resourceTypes": [
          "main_frame"
        ]
      }
    }
```

Apple Feedback Assistant Bug Report: [FB16607998](https://feedbackassistant.apple.com/feedback/16607998)
Safari version 18.3
MacOS Sequoia 15.3.1

**Comment by lenacohen** [comment]
Still an issue when I tested on Safari Technology Preview Release 215

**Comment by ghostwords** [comment]
This breaks our "surrogate" scripts and advanced surrogate API click-to-activate widget replacements.

This also breaks our link tracking removal workaround.

**Comment by lenacohen** [comment]
This was fixed in Safari Technology Preview 218. Will close the issue once the fix is released in Safari.

**Comment by lenacohen** [comment]
> This was fixed in Safari Technology Preview 218. Will close the issue once the fix is released in Safari.

Oddly, this issue is happening again in Safari Tech Preview 232 and it's still not fixed in Safari 26.1.

**Comment by carlosjeurissen** [comment]
Tested on macOS 26.4.1, and this is still an issue with Safari Version 26.4 (21624.1.16.11.4) and STP Release 242 (WebKit 21625.1.13.19.1).

Created a cross-browser demo extension: https://jeurissen.co/webext-demos/dnr-redirect-static-session

And opened a webkit bug: https://bugs.webkit.org/show_bug.cgi?id=313963
